const jobs = [
  {
    id: 1,
    position: "Frontend Engineer",
    company: "Lush",
    location: "Brighton, UK",
    dateSaved: "May 1, 2023",
    salary: "130,000",
    status: "applied",
    rating: 4,
    jobNotes:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
  },
  {
    id: 2,
    position: "Backend Developer",
    company: "Overleaf",
    location: "London, UK",
    dateSaved: "April 28, 2023",
    salary: "70,000",
    status: "interviewing",
    rating: 5,
    jobNotes:
      "Lorem ipsum dolor sit amet, consAt vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.ectetur adipiscing elit. ",
  },
  {
    id: 3,
    position: "Full Stack Developer",
    company: "Ancestry.com",
    location: "Chicago, USA",
    dateSaved: "April 25, 2023",
    salary: "90,000",
    status: "offered",
    rating: 3,
    jobNotes:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 4,
    position: "UX Designer",
    company: "Google",
    location: "Mountain View, CA",
    dateSaved: "May 10, 2023",
    salary: "150,000",
    status: "applied",
    rating: 4,
    jobNotes:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 5,
    position: "Marketing Manager",
    company: "Apple",
    location: "Cupertino, CA",
    dateSaved: "May 5, 2023",
    salary: "120,000",
    status: "interviewing",
    rating: 5,
    jobNotes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 6,
    position: "Software Engineer",
    company: "Microsoft",
    location: "Redmond, WA",
    dateSaved: "May 3, 2023",
    salary: "130,000",
    status: "offered",
    rating: 3,
    jobNotes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 7,
    position: "Product Manager",
    company: "Facebook",
    location: "Menlo Park, CA",
    dateSaved: "April 30, 2023",
    salary: "140,000",
    status: "applied",
    rating: 4,
    jobNotes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 8,
    position: "Data Scientist",
    company: "Amazon",
    location: "Seattle, WA",
    dateSaved: "April 28, 2023",
    salary: "120,000",
    status: "interviewing",
    rating: 5,
    jobNotes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 9,
    position: "DevOps Engineer",
    company: "Netflix",
    location: "Los Gatos, CA",
    dateSaved: "April 26, 2023",
    salary: "140,000",
    status: "offered",
    rating: 3,
    jobNotes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 10,
    position: "Technical Writer",
    company: "Adobe",
    location: "San Jose, CA",
    dateSaved: "April 25, 2023",
    salary: "100,000",
    status: "applied",
    rating: 4,
    jobNotes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];

export default jobs;
